- name: Creating Directory for font if necessary
  file:
    path: "{{ font_dir }}"
    state: directory

- name: Cloning Powerline Fonts Repo
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ source_path }}/vendor/powerline"


- name: Cloning Fira Code Fonts Repo
  git:
    repo: https://github.com/tonsky/FiraCode.git
    dest: "{{ source_path }}/vendor/FiraCode"

- name: Installing fonts
  shell: |
    find . \( -name "*.[ot]tf" -or -name "*.pcf.gz" \) -type f -print0 | xargs -0 -n1 -I % cp "%" "{{ font_dir }}"
  args:
    chdir: "{{ item }}"
  with_items:
    - "{{ source_path }}/vendor/powerline"
    - "{{ source_path }}/vendor/FiraCode"


