- name: Playbook for simple machine setup
  hosts: all
  connection: local
  roles:
    - common
    - non-free
    - photography
    - development
    - js-development
    - go-development
    - python-development
    - ruby-development
