pkgs:

  - libffi
  - libncurses-dev
  - libncursesw5-dev
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libsqlite3-dev
  - liblzma-dev
  - python-openssl
  - xz-utils



  lib_pkgs:
  - tcl-tk
  - xz
  - readline
  - libffi

cli_pkgs:
  - gnu-sed
  - gawk
  - llvm
  - gcc
  - wget
  - curl
  - git
  - make
  - jq
  - zsh
  - neovim
  - tig

gui_pkgs:
  - docker
  - iterm2

font_dir: "{{ ansible_env.HOME }}/Library/Fonts"