---
- include_vars: "{{ item }}"
  with_first_found:                                   
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: install image editing sofware
  become: yes
  package: 
    name:
      - "{{ darktable }}"
      - "{{ geeqie }}"
      - "{{ rapid_photo_downloader }}"
      - "{{ gimp }}"
      - "{{ exfat }}"
      - "{{ exfat_utils }}"
    state: latest
