---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: Clone GoEnv
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: "{{ ansible_env.HOME }}/.goenv"

- name: check if shell zshrc exists
  stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc

- name: Add go env to path
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      export GOENV_ROOT="$HOME/.goenv"
      export PATH="$GOENV_ROOT/bin:$PATH"
      eval "$(goenv init -)"
    marker: "# Ansible managed GOENV "
  when: zshrc.stat.exists == True

- name: check if go installed
  stat:
    path: "{{ansible_env.HOME}}/.goenv/versions/{{ goversion }}"
  register: goinstalled

- name: Install a default version of go
  shell: |
    export GOENV_ROOT=$HOME/.goenv
    export PATH=$GOENV_ROOT/bin:$PATH
    eval "$(goenv init -)"
    goenv install {{ goversion }}
  args:
    executable: /bin/bash
  when: goinstalled.stat.exists == False
