---
- include_tasks: "{{ item }}"
  with_first_found:                                   
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- include_vars: "{{ item }}"
  with_first_found:                                   
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: "adding existing user {{ ansible_env.USER }} to group docker"
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes
