---
- name: Creating source directory
  file:
    path: "{{ source_directory }}"
    state: directory

- name: Gather development setup facts
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "../vars/{{ ansible_distribution | lower }}.yml"
    - "../vars/{{ ansible_os_family | lower }}.yml"
    - "../vars/default.yml"

- include_tasks: "preinstall/main.yml"

- name: Install Development Libraries
  become: "{{ become_for_package }}"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ lib_pkgs }} "

- name: Install Commandline utils
  become: "{{ become_for_package }}"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ cli_pkgs }} "

- name: Install Graphical utils
  become: "{{ become_for_package }}"
  package:
    name: "{{ item }}"
    use: "{{ gui_package_mgr }}"
    state: latest
  with_items:
    - "{{ cli_pkgs }}"

- include_tasks: "postinstall/main.yml"
