---
- include_tasks: "{{ item }}"
  with_first_found:                                   
    - "platform/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | int}}.yml"
    - "platform/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "platform/{{ ansible_distribution | lower }}.yml"
    - "platform/{{ ansible_os_family | lower }}.yml"

- include_vars: "{{ item }}"
  with_first_found:                                   
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "../vars/{{ ansible_distribution | lower }}.yml"
    - "../vars/{{ ansible_os_family | lower }}.yml"
    - "../vars/default.yml"

- name: Installing basics, shell, neovim 
  become: "{{ become_for_package }}" 
  package:
    name: "{{ item }}"
    state: latest
  with_items:
   - "{{ basics }}"
   - "{{ shell }}"
   - "{{ nvim }}"

- name: Installing terminal emulator
  become: "{{ become_for_package }}"
  package:
    name: "{{ item }}"
    use: "{{ 'homebrew_cask' if ansible_os_family == 'Darwin' else 'auto' }}"
  with_items: 
    - "{{ terminal_emulator }}"

- name: Installing docker
  become: "{{ become_for_package }}"
  package:
    name: "{{ item }}"
    use: "{{ 'homebrew_cask' if ansible_os_family == 'Darwin' else 'auto' }}"
  with_items: 
    - "{{ docker }}"

