- name: "apt | ensure docker gpg key present"
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: "apt | ensure docker repo present"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} test"
    filename: "docker"
    state: present
    update_cache: yes

- name: "apt | ensure docker present"
  become: yes
  apt:
    name: docker-ce
    state: present

