---
- include: debian.yml
  when: ansible_pkg_mgr == 'apt'

- include_vars: "{{ item }}"
  with_first_found:                                   
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: install gstreamer codecs
  become: yes
  package: 
    name:
      - "{{ gstreamer_plugin_bad }}"
      - "{{ gstreamer_plugin_bad }}"
      - "{{ gstreamer_plugin_ugly }}"
      - "{{ libavcodec_extra }}"
      - "{{ gstreamer_libav }}"
      - "{{ chromium_ffmpeg_extra }}"
      - "{{ libdvd }}"
    state: latest
