- name: Run development pre configuration
  include_tasks: "{{ item }}"
  with_first_found:                                   
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | int}}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower}}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"