- name: "apt | ensure docker gpg key present"
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: "apt | ensure docker repo present"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} {{ 'test' if ansible_distribution_release == 'Disco' else 'stable' }}"
    filename: "docker"
    state: present
    update_cache: yes

- name: "apt | ensure vscodium gpg key is present "
  become: yes
  apt_key: url=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg state=present

- name: "apt | ensure vscodium repo is present"
  become: yes
  apt_repository:
    repo: "deb https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ vscodium main"
    filename: "vscodium"
    state: present
    update_cache: yes