- name: check if homebrew is installed
  shell: command -v brew >/dev/null 2>&1
  register: brew_is_installed
  ignore_errors: yes

- name: install homebrew
  shell: >
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew_is_installed.rc != 0

- name: Tap adoptopenjdk
  homebrew_tap:
    name: AdoptOpenJDK/openjdk

- name: update and upgrade brew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes 
